const express = require("express");
const router = express.Router();
const axios = require("axios");
const control = require("../controllers/index");
const auth = require("../authentication/auth");
const app = express();
router.post("/influencerLogin", control.influencer.influencerLogin);
router.post("/influencerRegister", control.influencer.influencerRegister);
router.post("/influencerLinkStore", control.influencer.influencerLinkStore);
router.post("/addInfluencerLink/:id",control.influencer.AddLink);
router.delete("/influencerRemove/:id", control.influencer.removeInfluencer);
router.post("/resetPasswordinfluencer/:id", control.influencer.influencerResetPassword);
router.get("/getinfluencerData", control.influencer.getInfluencerData);
router.get("/getinfluencerDataById/:id", control.influencer.getInfluencerById);
router.get("/getInfluencerByname/:name",control.influencer.getByName);
router.get("/getinfluencerDataByUsername/:email", control.influencer.getInfluencerByUsername);
router.get("/getInfluencerDataCount", control.influencer.influencerDataCount);
router.get("/logutinfluencer", auth.influencer, control.influencer.influencerLogout);
router.put("/influencerUpdateById/:id", control.influencer.influencerUpdateById)
router.get("/influencerLinkShow/:email", control.influencer.influencerLinkShow);
router.post("/influencerByType",control.influencer.influencerByType);
router.post("/influcerInstagramData",control.influencer.influencerUpdateInstaData);
router.post("/storeHashTag",control.influencer.influencerStoreHashtag);
router.post("/applyService",control.influencer.applyService);
router.get("/InfluencerInfo/:email",control.influencer.influencerAllData);
router.post("/engagementRate",control.influencer.EngagementRate);
router.post("/otpVerify",control.influencer.verifyOtp);
router.post("/sendOtp",control.influencer.sendOtp);
router.post("/SelectInterest",control.influencer.SelectInterest);
router.get("/approveShow/:email",control.influencer.approveShow);
module.exports = router;
